### ISSUE TITLE
bb-browser doesn't work with empty instance names

### ISSUE THREAD

**Issue by edbaunton** [buildbarn/bb-browser#10]
For better or worse, empty instance names are allowed by the Remote Execution protocol. This breaks `bb-browser` as empty strings in URLs a removed and `bb-browser` cannot see them. 

I initially attempted a fix in https://github.com/buildbarn/bb-browser/pull/8 however that approach was too naïve as it did not account for all other parts of the code that link from page to page. A more thought out approach is required.

If time permits I would like to provide a PR for this issue, although it's possible that #4 fixes this if the whole thing is to be redone.

**Comment by mickael-carl** [comment]
Hi ! Indeed, #4 will fix this, so it's only a matter of waiting for this PR to land. If you would like to verify this, you can check the `elm` branch.

**Comment by EdSchouten** [comment]
This has been fixed now. I did have to change the URL scheme of bb-browser in the process, as the old one made it incredibly hard to do so. URLs now contain a `/blobs/` component, making it easy to determine where the instance name stops.
