### ISSUE TITLE
Consider reducing scope of bb-browser

### ISSUE THREAD

**Issue by mickael-carl** [buildbarn/bb-browser#21]
Currently, bb-browser allows users to inspect build progress and results, using the Build Event Stream protocol. However, the description of bb-browser actually states `Web frontend for exploring an Action Cache / Content Addressable Storage`. 
Furthermore, due to how BES is defined, maintaining a BES service proves quite difficult currently and might not be worth the effort at this time.
Maybe it would be worth considering making bb-browser simply what it was supposed to be in the first place: an AC/CAS browser and nothing more?

**Comment by cphang99** [comment]
I would be in favour of this. I would argue that given bb-event-service is not planning on being [maintained](https://github.com/buildbarn/bb-browser/issues/12#issuecomment-570738973), decoupling BES from bb-browser will make alternate implementations easier to implement, and make the scope of bb-browser cleaner.

**Comment by EdSchouten** [comment]
Yeah. bb-event-service was a nice experiment, but there simply isn't enough momentum to turn it into something useful. There is also no need for it to be part of core Buildbarn. Other people in the community are free to build their own set of daemons to ingest Build Event Streams and expose them through the web.

I'll go ahead and gradually remove support for this over the next couple of days/weeks.

**Comment by mickael-carl** [comment]
bb-event-service is now archived. Given that, I'll go ahead and start removing the relevant bits from bb-browser.

**Comment by EdSchouten** [comment]
Done!
