### ISSUE TITLE
browse into zip files

### ISSUE THREAD

**Issue by gyorokpeter** [buildbarn/bb-browser#35]
bazel puts all the output files into a zip file. However these files might be a web of interlinked HTML files would normally allow for browsing the test results easily. It would be useful if buildbarn browser could browse into zip files instead of having to download, extract and then open the files in the browser.

**Comment by EdSchouten** [comment]
I would actually prefer it if this was tackled the other way around: Bazel should not zip undeclared outputs of tests. Doing so tends to increase CAS usage significantly, as a mixture of deterministic and non-determinstic files constantly ends up generating ZIP files that were never seen before.

**Comment by EdSchouten** [comment]
Hey there! Looks like Bazel fixed this on their end. Let’s close this issue here, as there is nothing left to do.

Thanks for fixing this!
