### ISSUE TITLE
README example is broken

### ISSUE THREAD

**Issue by Ryan-Draves** [buildbarn/bb-browser#42]
The example in the README spits out errors. `bazel run //cmd/bb_browser:bb_browser_container` yields:
```
Tagging 5e7f1b70b4e4c115311dfe09c7cd4817d10ba17a9d007bf83e7d7c69cc94811b as bazel/cmd/bb_browser:bb_browser_container
2023/02/27 20:25:57 Usage: bb_browser bb_browser.jsonnet
```
but does produce the docker image,  however `docker run -p 80:80 -v $(pwd)/config:/config bazel/cmd/bb_browser:bb_browser_container` also yields:
```
2023/02/27 20:27:34 Fatal error: rpc error: code = InvalidArgument desc = Usage: bb_browser bb_browser.jsonnet
```
I took at guess that maybe there's a missing entrypoint, so I fed in the example `blobstore.conf` file as an argument, but `docker run -p 80:80 -v $(pwd)/config:/config bazel/cmd/bb_browser:bb_browser_container "/config/blobstore.conf"` yields:
```
2023/02/27 20:28:26 Fatal error: rpc error: code = Unknown desc = Failed to read configuration from /config/blobstore.conf: Failed to evaluate configuration: /config/blobstore.conf:2:8-9 Expected token OPERATOR but got "{"

  grpc {

```

How do I run this?

**Comment by moroten** [comment]
The https://github.com/buildbarn/bb-deployments repository should work. Please give it a try.

**Comment by Ryan-Draves** [comment]
Thanks for the quick reply. I was able to get that repo's example working, but I was hoping to run the browser alongside a Buildgrid deployment as well. The README in this repo followed ~closely with the example config file in the [Buildgrid docs](https://buildgrid.gitlab.io/buildgrid/user/using_bb_browser.html), but I'm unsure how to translate the deployment repo's setup.

Running `docker run -p 80:80 -v $(pwd)/config:/config bazel/cmd/bb_browser:bb_browser_container "/config/browerser.jsonnet"` with the `browser.jsonnet` file in other repo gave:
```
2023/02/27 21:24:42 Failed to read configuration from /config/browser.jsonnet: rpc error: code = Unknown desc = Failed to evaluate configuration: RUNTIME ERROR: couldn't open import "common.libsonnet": no match locally or in the Jsonnet library paths
	/config/browser.jsonnet:1:16-41	thunk <common> from <$>
	/config/browser.jsonnet:4:14-20	
	Field "blobstore"	
	During manifestation
```

Is there a simple standalone deployment option?

**Comment by moroten** [comment]
I'll give it a try to sync `browser.jsonnet` tomorrow.
