### ISSUE TITLE
"Received unknown build event" : switch over event types apparently incomplete

### ISSUE THREAD

**Issue by ailiev** [buildbarn/bb-browser#9]
Locally added a printf %#v of the unrecognised event:

```
&proto.BuildEvent{Id:(*proto.BuildEventId)(0xc000512690), Children:[]*proto.BuildEventId(nil), LastMessage:false, Payload:(*proto.BuildEvent_Aborted)(0xc00000f4b0), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
```

**Comment by ailiev** [comment]
The bazel is slightly patched on top of : Build label: 0.23.2- (@non-git)

**Comment by EdSchouten** [comment]
Hi Alexander! Sorry for not getting back to you some time ago. I was ill for 1-2 weeks some time ago and have been trying to catch up ever since. :-/

The annoying thing is that `%#v` doesn't give us insightful info about `oneof` fields in Protobufs. Could you try to print `.Id` or `.Id.Id` directly? Based on comparing the code and the build event protocol, it's either a PatternSkipped or ConfiguredLabel event ID.

A copy of the raw build log would be very helpful to have, but if this is not possible to send over due to confidentiality, could you maybe let me know what you did to trigger such a log/event? Thanks!

**Comment by ailiev** [comment]
No problem Ed, speedy recovery!

I got the additional fields, indeed looks like ConfiguredLabel:

```
rpc error: code = InvalidArgument desc =
key.id=&proto.BuildEventId_ConfiguredLabel{ConfiguredLabel:(*proto.BuildEventId_ConfiguredLabelId)(0xc00014d680)},
key="configured_label: <\n  label: \"//:custom_jdk\"\n  configuration: <\n    id: \"533c86ee83d6711e6912e67203106d4a\"\n  >\n>\n",
event=&proto.BuildEvent{Id:(*proto.BuildEventId)(0xc0002dbbf0), Children:[]*proto.BuildEventId(nil), LastMessage:false, Payload:(*proto.BuildEvent_Aborted)(0xc000318940), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
: Received unknown build event
```
I can't send the build log without checking/sanitising its contents, so would try to do without for now. It was a normal build of Java+Scala modules, with a simple --config specified, successful outcome, 100% remote cache hit rate, as I had run the build before. The error is from loading the page for the build, as reported by the bazel client.

**Comment by EdSchouten** [comment]
Hi there! I think I managed to reproduce this by doing a build of a project with some unresolved remote dependency (removing an entry from `WORKSPACE`). Can you try whether latest master works for you? Thanks for reporting this!

**Comment by ailiev** [comment]
Thanks for the quick attention Ed

It's not fully there AFAICS - in my work setup one of the validations fails (it may help a bit to make each such error message unique, I think there are several instances now)

```
rpc error: code = InvalidArgument desc = Cannot add "ConfiguredLabel" node with ID "configured_label: <\n  label: \"//:custom_jdk\"\n  configuration: <\n    id: \"533c86ee83d6711e6912e67203106d4a\"\n  >\n>\n": Value cannot be placed at this location
```

Looking at the proto, ConfiguredLabel is mostly implicated with visibility problems, and indeed I have that in my workspace, suppressed with --nocheck_visibility . An easy replication would be, with the bazel examples repo, in `java-tutorial`, comment out the visibility line in `BUILD` , then `bazel build --nocheck_visibility //src/main/java/com/example/cmdline:runner`
